# Generated by Django 5.0.6 on 2024-06-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=128)),
                ('ceo', models.CharField(max_length=64)),
                ('headquarters', models.CharField(max_length=64)),
                ('foundedyear', models.DateField()),
                ('typeofcompany', models.CharField(max_length=64)),
                ('primaryindustry', models.CharField(max_length=64)),
            ],
        ),
    ]
