# Generated by Django 5.0.6 on 2024-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companycrudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='foundedyear',
            field=models.IntegerField(),
        ),
    ]
